- name: Add extra sudoers
  template:
    src: extra_sudoers.j2
    dest: /etc/sudoers.d/extra_sudoers
    owner: root
    group: root
    mode: 0440
    validate: "/usr/sbin/visudo -cf %s"
  tags:
    - common
    - sudoers
