- name: Create user "{{ item.name }}"
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    createhome: true
    append: true
    shell: /bin/bash
  loop: "{{ root_users }}"
  tags:
    - root
    - root-users
