- name: Add Docker repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - x86_64
    baseurl: https://download.docker.com/linux/centos/9/x86_64/stable/
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes
  tags: docker

- name: Install Docker CE
  yum:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present
  tags: docker

- name: Docker service
  service: 
    name: docker 
    state: started 
    enabled: yes
  tags: docker

- name: Docker-cfg dir
  file: 
    path: /etc/docker/ 
    state: directory 
    mode: 0755 
    owner: root 
    group: root
  tags: docker

- name: Docker-cfg
  template: 
    src: daemon.json.j2 
    dest: /etc/docker/daemon.json 
    mode: 644 
    owner: root 
    group: root
  when: docker_daemon_json is defined
  notify: restart docker
  tags: 
    - docker
    - docker-daemon-json

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  tags: 
    - docker
    - docker-compose
