- name: Upgrade packages
  yum:
    name: "*"
    state: latest
  tags: 
    - common
    - common-packages

- name: Install package epel-release
  yum:
    name: epel-release
    state: present
  tags: 
    - common
    - common-packages

- name: Install common packages
  yum:
    state: present
    name:
      - vim
      - screen
      - atop
      - lsof
      - tree
      - git
      - lshw
      - iotop
      - telnet
      - pwgen
      - bind-utils
  tags: 
    - common
    - common-packages
