- name: Setup RHEL9 as docker host machine
  hosts: rhel9-docker-host              # change this according to your inventory
  remote_user: root

  roles:
  - roles/rhel9/common
  - roles/rhel9/services/docker

